with-expecter: true
packages:
  github.com/green-ecolution/green-ecolution-backend/internal/service:
    config: 
      dir: ./internal/service/_mock
    interfaces:
      InfoService:
      MqttService:
      TreeService:
      AuthService:
      Service:
  github.com/green-ecolution/green-ecolution-backend/internal/storage:
    config: 
      dir: ./internal/storage/_mock
    interfaces:
      InfoRepository:
      SensorRepository:
      TreeRepository:
