dashboard:
    title: ENC[AES256_GCM,data:/qaySCo4Llrd9DGi4crsaTxNV0PslIyctA==,iv:a8RTDOgqR8C9a/K/uZPV5pJKour+8xwTdODx/zStpF8=,tag:D10JoWIt9cW+Vc2DkxFaig==,type:str]
server:
    port: ENC[AES256_GCM,data:JNO1OQ==,iv:anKjUkpIvXysZKyhxCnkh0YpJImd0y5T0dt8ZSkjwJg=,tag:20VlXPIhLRN4ei04tFOhVw==,type:int]
    development: ENC[AES256_GCM,data:x3MqXw==,iv:rZOK6loHI589VgMCBMvGKwYYSZQSdGffpLngMXFvIeY=,tag:fwnuEs37bpywkfb0o6iD5A==,type:bool]
    app_url: ENC[AES256_GCM,data:d0WfF8+BDloY4iM8e3qJcSDD2ROO,iv:SM5825GVWyrlyKUamlhAMl/mWFm6BvdcAqe3aWf5CoI=,tag:6zXn289vUFot9RMOx48RHA==,type:str]
    logs:
        level: ENC[AES256_GCM,data:srmlFhs=,iv:XrwgB12pLz0jERUsBd3Zzs9CQ4nVFrgxIhkVmQQX7MA=,tag:Od8rTL/0T9Z5p5QSH5YF3Q==,type:str]
        format: ENC[AES256_GCM,data:XAlh/w==,iv:u9GLxwxNiVDap/Dy89IkcYmD8ROPIYlzq+Hlmg2xh7U=,tag:6Kcz1odSZTBg8I318GRpTQ==,type:str]
    database:
        host: ENC[AES256_GCM,data:lG8OaQH7J0jY,iv:/Df/xbruxpW5R72w65iDfx7mJU9cxVmPRG7OTtxL2Ak=,tag:sRSCkO2o7JZOEKfCwoV6qg==,type:str]
        port: ENC[AES256_GCM,data:HVdXtw==,iv:y3TrSkEN8/gCDjjV/Xgf82QuYJP77F8en4pilSkZwwk=,tag:PpAnxDbYDYtkR/SZuPmCyw==,type:int]
        username: ENC[AES256_GCM,data:O4SJdyVUOHM=,iv:OW7fdwAAgzx7UiQrVWPQIs0n4f2GHJRA5TlWA/p3TN8=,tag:IcYKMdvU14I19tXwvaA4cw==,type:str]
        password: ENC[AES256_GCM,data:vdEdn6hadX4=,iv:HV20mzI6wjVUWdXaACdVge8xU1wYy6AwsmXMzkWeVNI=,tag:OdKtNeAEwu2R74/1uO1O8w==,type:str]
        name: ENC[AES256_GCM,data:zJB8tyd6J0Y=,iv:8Ia9GFlYPjsWPnjcK4LLNIUxGboZkg1sqtC54hhwOiQ=,tag:3HsW7XdUk024lDGxZifq9Q==,type:str]
auth:
    keycloak:
        baseurl: ENC[AES256_GCM,data:j+notNxiAEfT6B9LAFAa04oF3TxgZw4QwYRPRXwvsA==,iv:SBAALSpJwi2frCV20CeiveEHoRylt5pu9p8DebVLDp4=,tag:vOk2Nfh1Lj+vIuO68eaRdg==,type:str]
        realm: ENC[AES256_GCM,data:0m3wY0ExdIeCVvslwn1ngUPOUw==,iv:91s1geN4Q3rPS8TyBR3EaZOwGA5ioMofkygbhrV6Ea8=,tag:Whg0UiccCm8GvKzkolIS5Q==,type:str]
        client_id: ENC[AES256_GCM,data:qlVIVrZj5q+eJLBWzvWSZa9jhsNZjw0=,iv:mJZfBTcBZwX45S9MdjKpYWgfIj1XHy3gE8jIpglcMDc=,tag:A21UBATsIkLtWNKm7Rtffg==,type:str]
        client_secret: ENC[AES256_GCM,data:pse0VOWjz+MBnCnTg0UA5eyyc6xJO6KXKC8qFwOlR4c=,iv:EGPkZqhOhjT+8jXDTXZ/QNV8BQ1KDeRHyMgoD9WfUvI=,tag:9Lb1lfoeOe4tC04xWm20DQ==,type:str]
        realm_public_key: ENC[AES256_GCM,data:jvJs5CQwcSUl0ZXOZmFz4saqcBjUQ4/NHxpMFct/wiL/slZZnnIDmymOjNUuOd/So4jfvo6P6d2qWAGs5TUDq16UNFEf+/f9OsbdGqRUcd3LIAIE6twEeDOrI7GSU0UPEdc8/bWZDFTXsvkGHm0QnLMkXhPtiChHWtgkw7RKzylunQcVOt2DPui7f+pPTjMsGQND3QlCuJ5W8jBNb5sGhILqlZ6NuID67n/zDUEpxmQwALSENuTx69bg+MSHK3YXX9Uv6lsW/eRzyyydzfkrUM/qM+qyHUmTc5U0fQYbqx2WCg3wCcr+3h4l6G5pcbOkwTSw8vvYEneWRkE4gecgwUqiHvwxkn8bJ25CzqV17F3cA4YMMNIN/paaeIoFZKV8zj/ciNhOnbKDI1xediu/RyFQim7N/TMBsOt2GFjLUByfn12ATRMbj9Af8ZPOpBtN/ad/6SBbDy8bvQBeIOCessW/pekkEYK28bV8nVTtusr+jVbhy9V9lCo1SPd0vNTSrTwYBpRMRPw=,iv:XUkC7AK+O9ZO5gth5O1xYcgA79oLxYuZOcKZuU6heGg=,tag:YbUMA1TH/ImsfWtI9XriMg==,type:str]
        frontend:
            auth_url: ENC[AES256_GCM,data:P1haNTqwaqy2UKBBo39OV3OFwb7e3CxKGHTRMRGQJniMwZBAh/+qyuCrN4ptppfwyfK1Q7Q8xaMOFoLDnjdknzRShnfIMmSVLoRK2y+f0bQ4gtsodHTw,iv:ob5na/3kcEOVYQBlXfPPh3MPigqm4Pqbcqh8RsgVi0I=,tag:sYFQNofc0ceWZOtZ+4XICw==,type:str]
            token_url: ENC[AES256_GCM,data:Fmb/9Fs6J1DZyfQrtlMFHnxLf3e42mphbppo7VlVzIIOCfdDshuuCyOkgatqslRmF4jxKW2fPI7lJzxLjHrdr5tyhzBhfFe01dKLHQQ8jpfhkivQfHWX7A==,iv:UH9BaOYMn+4bpBPXuuqTHm2TNgFEf0DkREaIPFKhHHM=,tag:Cn/dHixXCmHqmKcOFYaEwA==,type:str]
            client_id: ENC[AES256_GCM,data:keSjjtjUFzOxy+A5PYB+vY2gFmnyiHcE,iv:Ze8C0Eyef672gwXugZohpHpvNphR3lXR1Dh5FAjG/II=,tag:SG2waRjb8k7vvsacaNZBfw==,type:str]
            client_secret: ENC[AES256_GCM,data:j1bqkspnP5lvP9Jf3usXHetWTDXIqFeI0KDgO4KFJpU=,iv:NRjlLS/IHEeepFGDHi04qmYWplDtNdIBpYJisgWrp1E=,tag:DWanJjKR2AZo/PGMVo4D3w==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:TJ2wKn+rSj/zfmuSkRuZ8YF1/aPfXQpOwWcWCGA80EvXLVg=,iv:qRTayRrNnYOYUdzYgciRev7VzCSPLgeymgbK1pD+O/4=,tag:VsYYot8MYMOzgsSizI1Fiw==,type:str]
    client_id: ENC[AES256_GCM,data:FEnao1F6e2zqrxw=,iv:nuRl9Tgl+2mBc3ypOZTTnKYQeCX5o9BHqFPTAzg+/I8=,tag:ijL6RRxDVk9VFap7/1zaDQ==,type:str]
    username: ENC[AES256_GCM,data:0X+6MdXTx1OmXlF/eSpwwA==,iv:qcQ2vcjFk4e++KzxPwFIm7l95QryQIqqVhzwvMxaN5o=,tag:jV0ToWJ7MwB1fObtrOZ2zQ==,type:str]
    password: ENC[AES256_GCM,data:p6VZjFENsFlh7a+biTaNPQ5d5ZuqjEpi0VGOGjgis9N/ZypOZQhPHTDoNEoLR64iaRj5apMGQ4IBFVrk+E9IVnfLrk9aw+VPf9sBt9VSNNBhLmN+GUpB9WmGZo6HWHOGtLw=,iv:wh1MsRqCiJGxTEBYGHugqTqcyOqndsaAviYoLFWPuLs=,tag:wDfo4dDw7ihiUiR5moK+YQ==,type:str]
    topic: ENC[AES256_GCM,data:urXwS7n1hFoVI9Wm2Eal492VHYTGYy6/mogpeM9hYcbaulM9SfN1XVhJ,iv:x9He4owd5pAcVtgxTugv7sE4g2Vhq4hRA1zUkpdJd+4=,tag:YTwBZX1i7j54j9EPVTNbNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU3oya0hsQ3kyc255c0Z6
            YUtRRzZnN1Q5SXNYNjlxcFlCUHMrYzQ2UUZBCmxZdG9XTVZNV2wvaFk4dHUvWFFw
            cFJudVRaelNTOTJ4TzZ5QVkwMUIxd2sKLS0tIFo0aUNXenR6N2N4MWlSTENnWTBN
            WXhNQTRaak5lK0JDcHdQTEx1cFpBdGsKEe75iIt2yBzN3+bSwhaOVqNifP1QCJiw
            9iQ0d9Fyq5bHrCkiOXn9iUFZwX95xw/SIsRVJAchEe4mu7cMg1mf0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T15:14:47Z"
    mac: ENC[AES256_GCM,data:e/U64+uCa8kah73UX9JKI/p6F4hpdgvdyv1LqmGyTSFAkk3DMWAKi+ruCfm4taE3bRvCtEcE6vDcy4rTzePF4avIgZ4NSVXEfXH1q6TLkWXB3qJ31ftSjq36+L+tmY9FyX1zbp8Wff2YOwhRDYyvAbMyztewwBLK8VaKp0bNmHE=,iv:qAlWjr8bBaOjJDHxlcj4+8xWOB9qCJ8CZpvCYITky68=,tag:d0/3Ex+uWz/6Jl2RV/xi6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
