dashboard:
    title: ENC[AES256_GCM,data:25dEauErruZN/I/cyj8hT6TBW6IHFoZL5g==,iv:+qTJocmkIQexbwc+0shc1KNWfgVds1BM9LR3WIDRYYs=,tag:XbVQuhdZKrHNboRx/PXPaQ==,type:str]
server:
    port: ENC[AES256_GCM,data:HtDBBw==,iv:o/g7hhyW2tE44W1CL2kWMgVLFLO9MJ+37tKPGCBOgOU=,tag:V/uyL0GCsHkjxqIilLZ0nw==,type:int]
    development: ENC[AES256_GCM,data:NanfgA==,iv:GtVNRqhn+zcG/n+BK04JnC8P9ssuWGcmZYFYnHH77ao=,tag:cl7j/1lQwe0xBfOXctScvQ==,type:bool]
    app_url: ENC[AES256_GCM,data:AjT9KBOrxviYgWhEoNVpYQ3T36P1,iv:B+fVy1dCCQjA4ztn+MR9PZzLAbX37yJiPkRFyM59Ibw=,tag:AkXFi81VJTTP7XbeFOKzyg==,type:str]
    logs:
        level: ENC[AES256_GCM,data:sF3rtgM=,iv:L4aAlYXDMIHMrV6+AInc2FU1upoWXohaRWj8N6U8AHA=,tag:Hd4/e8BLWcLFzD+WhVbaew==,type:str]
        format: ENC[AES256_GCM,data:20TKVA==,iv:U6D7r+h5m1sdEBudho5y/kb+cVu6wHxEVjtLUg/v8xU=,tag:JCRRQhTkYQtJKYxj7aMB0w==,type:str]
    database:
        host: ENC[AES256_GCM,data:/CuyrVhEexYZ,iv:JUM1B/WC0aeL5z8hqXRNMnl0qj2iLQ7zWVW8FW6ARuM=,tag:xE5N9rLYfzsAm4elyHPreg==,type:str]
        port: ENC[AES256_GCM,data:9yJbMQ==,iv:4RaFCZdzCu5gcJJd2llHXIvl29pKxBq47ey9sOLfrdE=,tag:0dzNHwNchfOuEiJPwK+BdQ==,type:int]
        username: ENC[AES256_GCM,data:UYG0lgQ2NDA=,iv:n3HxSrbQST1A3W8NeqDViBAW2HsuaQSTiGieGgj62eA=,tag:Fxvh/Bnn+v6BB1/0dGw9Yg==,type:str]
        password: ENC[AES256_GCM,data:bPlh0MABtd8=,iv:Ot6E10QNLUPa/2/zUlcaSMpmVqTfkT45bCiHog1aCDM=,tag:sY8GVFNp4nxesSO7jl+OKw==,type:str]
        name: ENC[AES256_GCM,data:7wbnwEHySBE=,iv:cuuai5PEW/czYgqS5MmrwuIcVOIGaWOKuZLAJbEotMI=,tag:q+1IrvEMHHvwVMm0YHuIFg==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:CzbFgm7PWAcfZt1Rcs/pfz4KY1w9BeMoNRwH/rEXhQ==,iv:sGfxfeFh0ZEDXnqtgL2NOpSMKXGd/Agp32sjJvMipK8=,tag:TLagwF+YeoUvwNp9+xAB0w==,type:str]
        domain_name: ENC[AES256_GCM,data:b/hQDmhYR1SpgaPVPXZGLLyrKg==,iv:V3TwwQVGu/x/XUtU2Axikb1ZyArzdYdYJIdrL9J5XJc=,tag:hwRD9QL2/CPDqokQxCLYpA==,type:str]
        auth_url: ENC[AES256_GCM,data:KiAlEbyNenfgQT8Djr1pv75FmJXUmcjmqAP9mqEIdv9Y2LyC1xgoBTApFpjMc98ZuiJQIMipYhh96UevCSQFek5xT+OSiMS2GXSdeefltSwLEjBmBBn7,iv:HTxe1C+G+bPyUM9W1QOjntypG7m0NA9S/RfUQzrdEao=,tag:caRewGzCfMu6K2aGd1I5og==,type:str]
        token_url: ENC[AES256_GCM,data:oegbc8fplelrxYP2XKc/2Q69t3VNi7D1GzSvCM5JE/VetE/awiWg1kRU40ewoVi0+jMX/tGAJw4aFb5ivXJu/y9P/0fx7fWAllseu1nAsT33KcKoc8QBNQ==,iv:nqgjm+Y2HX4Wj1qDNKIEmjoSSIzjewZWTlCPc4bDB8g=,tag:Nn2xTqxGt0AbAVJGRJI+eg==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:aEz5iLnnIAJxQZRwFLxhXYCHZZUDRhKRnQHlf4Y8p3Q4t7LmGDC5ga4uONLw+Ujd+eGjH042TCVS4aPainqhk21oy7/4Rt20UXWFGqA2dAgufFUB9PexKQhXLBnuoLr4P6QKwwQGIybd0rrAJWANhd4MQb7oN066Q/g/iBCVs/qHQPJoaCHot1BjEV1UP2CzS2HD0UZbMLBjDq+sPVd+dSq6+TyzGgSnWiIL3k/dTB6Y6Jn6dmbAxbHe769s1rZvtIv1ShkxSsoEngKt/xxkGEonptdi2Pndvdoyrl5X+mm/IB+ceenMQI+o8caT1VW93Cf5jaqFCbnSBCo5JtCMFi97Z9mAwnGtV6p8OcxtGIXCIdp5uH4hw59387vJQGwrMT+qVYx2nVuY3CPpUcY9und0TPNML+kVECf2fkvjKE8c+DGKAVKnC94c/tBLSc2Avm5ZSwXlw7QpMLcTY4bZGnHTywxwQ3nwKFwoBNVq1ZgZ/QJSQPqtIPma7vV1r/YWd/Gp81AoXbY=,iv:ooEBRrrD2NiNcnTg2xG4+16C8qF3iXhz75w1Q3HCibU=,tag:0xqnTojl1m3NOShkcPbI7w==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:ahruWd4U1CGHAjHJxXSumCLh5mMgxk7/,iv:t53GdwxJBdabNiJ8ePJ7t78wqihD/jgd8+K8VWoqxa0=,tag:fAsbZkL8sfurCeRzA+Z32Q==,type:str]
            client_secret: ENC[AES256_GCM,data:rD9gVwhQ3Pyf03ahqSOw3/ZjdVB+ydKmONZBrdgdc3E=,iv:Zr/U+GvM5DxieFRkg/hDWs8zsQRz1BtpzVxuhjR2iow=,tag:lgWQLGsO7fSPWRpw7SLMaA==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:5KKV64Br/PueiEfahhjm+EnhDfr8VxY=,iv:COP7TQFxNSZFCWfdTQPXGDppU2aAvzItePR/O8Ix45Y=,tag:WaVi5EgoL1KiYkVysgC57Q==,type:str]
            client_secret: ENC[AES256_GCM,data:KS8VOk0yNQg3vIC/9aBSb/dETKbYa6zKtcZIwW0k5+c=,iv:bHSH1mf2Op86ydpgo7+HDQXhs5H4KR5muHDJyjB8/qg=,tag:OE1/Wb6nTGJno11eE63ZLA==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:1iJ/bcCYUwy4UnRP0prnxDxcHydW4g2pua6BUhpc44Li854=,iv:lxLEZF7m5KdJyU0eIKHPdVR3T+TVA19ngfhHZF8ZLug=,tag:qwoA3UQDdG6kF9OW+9gqJg==,type:str]
    client_id: ENC[AES256_GCM,data:5N3FlTQ22QVOogI=,iv:E+DjZ1qtMDdCi0owcAc3e3nQoIq1VdBErbjJx2xREfc=,tag:y8rN0cGGEu951hJ0sLSiqA==,type:str]
    username: ENC[AES256_GCM,data:l20GJ6BTr5p3pQCX3UnXog==,iv:hixvLAq4k01CQaPCjQX0cbD7ZH6mVkEkh0DV++5kHa4=,tag:bVSl/2NZV1qxv6yF4DNt2A==,type:str]
    password: ENC[AES256_GCM,data:DB7Z5ZL+9xN2TTtddRxa7v9WlFAeAol50SpAcFaleghuZcyRoDNiVCn9WZmG7dMMCSR+xNu3LVxdP8fIa6JzaW5UG8XOEiMD03UrMXx3Gibq2vrK7Ks8pT0RffoZPl0bBBs=,iv:HdUdHQcLFTz9cTm0fvQMPwqgDomtwI9rJSWQab2jQBc=,tag:8m1YJUSrtVRwUGlUh6ikgA==,type:str]
    topic: ENC[AES256_GCM,data:S5pORfUQkmlPNXD9CAbrj7H3Neu4LgBXtxu3Tn7cB0tXyhS//FtMwlAe,iv:MZEmPRw6E0MehPdyD0RSU+juL+IC++pL9yD16+zzpU8=,tag:Z0kXyqFSj1dfAWdK/+7X8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeTRtMi9HZHhTZFpzUko4
            OTNaaklnUUlCWkdMZDJpb3F5aWsxbTBxbEc4CmhsZ0xYbFVyL1dFUSt2THlPQmZS
            cjI1TDNiNDlEWjJoY1Z0T1AxTVpjbzgKLS0tIE1YQXRhYUNTU3BYU251NGh5ZUY5
            Y1A1QTVZTllEbHRNNExWM1hkZXh5NW8KdjuetSUG9cwRQKR/Dd0+PFaFKgQGTBzl
            rr9NLZhurBHMF6pDkoTtuUDoy5Bk/sUkwe/QsOc16Rc/spAqC82guw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T17:10:49Z"
    mac: ENC[AES256_GCM,data:PXyo9ikHcQ+5uKQaN3aBtPffHRpFiO6S7V20ZqbRvt/lEp7WOFRVzfqx/RP02XsA/mgx9EnRYpNnnz5Og2Pj1RxaBJ0TWX8rB5KqItfXJ0V6/IVyyY8OM82ZVMrn7k4zsx2IQ5fPwGBQ5V/dEpVFowsvy4T9c/i6kvmPslAxfww=,iv:L8jsVB1CXZZOG0rc1YiHyW77e5+qC5YPk9T3aZ5xKfw=,tag:ZrtJEguZIMSUl3iESK+HAw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
