dashboard:
    title: ENC[AES256_GCM,data:zf6BjDDmjoU85jmNuLUEzX/JbDPbiKWjmiEgzL+z/A==,iv:9o0nVZIBsXe0mzsCDEmmCpYMy7yRQQqkbhKznpQVGKE=,tag:gWkX9v7PGdOGUy7mV4zyUw==,type:str]
server:
    port: ENC[AES256_GCM,data:I/NQuw==,iv:Kx+LNuE2mkJTlGiOihJeNd1/qPgcyCglcSzssnL16iw=,tag:0m37lSCE9OX9OX+Mx+cUoQ==,type:int]
    development: ENC[AES256_GCM,data:udXi5A==,iv:1V20n4OdmN3NEeuXhR4Q1NxEWdOyFKm7qQDLc43/e+k=,tag:b1NwQ/rXxCiIw5glgzM+fw==,type:bool]
    app_url: ENC[AES256_GCM,data:yZMMIdG2TCUpWyAY5Ug8Yitnc4f+,iv:4O+ytPpsYS6kWYha2TlNYObfbhHP5v/PiJHXuhzmfF0=,tag:YQWvAlt4PQWrCRC0xTFJWw==,type:str]
    logs:
        level: ENC[AES256_GCM,data:gXFwNFQ=,iv:kNYT4PSecxEsKomTosmJsPBcjhyDAsjhS++1HjxRB6U=,tag:lVDrqK+EsQE1NNZPcT0YVA==,type:str]
        format: ENC[AES256_GCM,data:9VZgsw==,iv:r68xqcU/juUk31bYLSQEcsfyQzB9tQZ6sArFg25j1QI=,tag:X1dL0YO7uBFkM4jX6ujjfg==,type:str]
    database:
        host: ENC[AES256_GCM,data:jCAmR/Sn7xg2,iv:HwCDqoYxV7bQ0j6n+DDT++wIzFEbddwe3uLyrh3igX4=,tag:nTFkJto7fTS1Jo3FBsfSRQ==,type:str]
        port: ENC[AES256_GCM,data:O63+KA==,iv:cJrwBenfeW2ZapWPDLO8pUhhMmJQY9S3m51FQ3fhO2w=,tag:QpdLP/ohLV948R+qXjSR5g==,type:int]
        username: ENC[AES256_GCM,data:JbkLYXDm3Bc=,iv:+U8yIuhFqQMZq+tsXgBbSz7JeiWZZHw3HrMt31NqXIQ=,tag:w0G0F0Igowo13CG/7pZ1mQ==,type:str]
        password: ENC[AES256_GCM,data:8NeLNjzLDgc=,iv:cYrJHsCK6QVEDM2nZ1hjUQtHBLnbGBvDoGVPaeHX9mY=,tag:G5bd6XkcwWJVXOpxJ+bV+A==,type:str]
        name: ENC[AES256_GCM,data:l8YQ/AArZmk=,iv:+q1CvIIxjGvCSUYwSjTj9Yc2+OHS+G9psUx6+jssyCQ=,tag:BCvtkAuRa3pHjNwTKvzmyA==,type:str]
routing:
    start_point:
        - ENC[AES256_GCM,data:qAypGG8cYvzijnONzyu7hG0=,iv:ie0bbDwqtICNCaVuG9njOS3GjPFqQKzsawRIwqqONjg=,tag:/AIwtJGYtw+mZ1IeBFac4w==,type:float]
        - ENC[AES256_GCM,data:unhNNIQ/MTx7TpxzJrKr3I04,iv:NwGqPufAI+5VPNPnF04nfZDZyvdzhBHpk17JjUZPHP4=,tag:fjIbu9Acs+Z5X6JudqXvUg==,type:float]
    end_point:
        - ENC[AES256_GCM,data:x34i/p4+/hoIEi4UYjSp40M=,iv:YzpKLy0AWybdecczfXJi3iw6vyUDRv3oPna16DZAxcM=,tag:NIbXFHh98LS2d1t55ZrSvw==,type:float]
        - ENC[AES256_GCM,data:MQg0jAbViFuEC3uYJOp/WApU,iv:SBbMitQov+bekhtiFIBMIYes2+OlR02n+VHLSyW8tJc=,tag:JBTpyX3h9xCTe5Tc3Sw4Tw==,type:float]
    watering_point:
        - ENC[AES256_GCM,data:isq2OnE/996A8aGElu4I6b4=,iv:aXNgptwyfdr7Seq0TYglgTqBT53OKin39QkrtYLjTCQ=,tag:wLxWouIpxKpyEzEpBs56hw==,type:float]
        - ENC[AES256_GCM,data:IgIiUThSCCX9g7ToZb3QihcE,iv:QxFnm3x9G1xmzKGWbJRag3fcNFhk/YfJTBOs3Tu/X6E=,tag:FdjXH6ueMRcqynNFBAvDmA==,type:float]
    valhalla:
        host: ENC[AES256_GCM,data:1/h7RzLIe8sU9NjW8pelnIBBcm6Z,iv:vK+NpR0TA6bA8z/n592IvJAsJc9+sBwu/8Pi4AL921M=,tag:cXo9lpOgC7hsZ6SxKSRtvw==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:cHthbiDYFkINr0fVvrsYNmmyVNvo,iv:6qp7rCGU49RXgPTzmNEhvftnb0RtOdNhqqY0Ig1wijs=,tag:RB1GAiFndFjy12hAWM5giQ==,type:str]
    ors:
        host: ENC[AES256_GCM,data:yKWAiTJiEhkC5OOzV1wQZYIQ8p2rpHNs8Q==,iv:bfAjDM//t35F33hyRQ3UM1rRVqu7vhfotDy5EpvyLFs=,tag:wsHD6k9Vy9GD2cPAOyLlog==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:5wm6HBHoWJZQI5yd64SraNPiDozm,iv:KFKVry6QH+50iayK67Lk/gyCNHYnf/xItVpZDMmVpsk=,tag:cojTFrMIAPxrNXnWWzud8w==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:VnBolPo+OrpoXFNR4YEWiPi6WhGj,iv:RlKxXE4YpmheCNgdLMX+YGKZZnTIXAeNvJvLhbVs+rI=,tag:MwrYmrn7hvuPLK9o2tPKhA==,type:str]
    region: ENC[AES256_GCM,data:SJxKwIqk8F+5,iv:8CuXfIOkU2PZLeRa6SOpVbWrVi/qdukYmHPOsOFEiZE=,tag:T00yiGGezXQqTZM2r/nIzA==,type:str]
    use_ssl: ENC[AES256_GCM,data:kwfIFw==,iv:s1dJqlNBRrmEUszWCgvyEYFi1hqiwuNyLAl6BKv7jDk=,tag:7OuLusxKC6uFoHIacKd6cw==,type:bool]
    route-gpx:
        bucket: ENC[AES256_GCM,data:9jP5ZyGIZ8okSQ==,iv:J9u/v+n9aMLaP1IqCBvAHLKbTh7KCePbmj9h748ySD0=,tag:xs0R3R4v3UiTnbX12EOmAQ==,type:str]
        accessKey: ENC[AES256_GCM,data:V9S8evz4pdvwug==,iv:bma2ENZXeRaPzrvZ0VMAiUCpp+fRFzKkjZtLSc8F5ok=,tag:1pevSy+jKVx8dJVyxQ5WIg==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:fgDG0sHuJZu2AH3cjAqbMwv47eLayd/Ys66uZqHOYvo=,iv:tIjBReYfC5OmcDvvVIYvfQRnrgq0ac50eZW6jN8jRH0=,tag:CSV4CUZLl9rhQG+320fbaw==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:+YoAnKjqCCM4Mh6s0mNcZ+mpGTr+uTxtA4m4uhw1Ig==,iv:fGOGC1HQ8F8vU8OpUqkquzKxOvXyR1BeUTCkZjEV3p0=,tag:wRqa6IKZu8r5p2994dpzZQ==,type:str]
        domain_name: ENC[AES256_GCM,data:vmnLzD8cd2bdGAGUuRh7ShRFdw==,iv:i1SvCpjoCIomkjl0f0CO3ortXhV+gLknqmmqExk/MSY=,tag:yfzcZcECN/NuR9tlPu8lTg==,type:str]
        auth_url: ENC[AES256_GCM,data:EXjZOp75ic2liQNsJtLo3oGecahG6ZZPpQ2ukpu3+glaEjzm+c6lkHYpprX5eyOnw0w8QD7oHDDUm5rQ4jYm8g3zTQwaouU8ROjrI7U4z2R95v1ylaqo,iv:uYguct/8GlYAbdaGnTA/t/8luCkAzdJjI2t2W4wHrKk=,tag:nNtA27CdIdUBLhciotjKDg==,type:str]
        token_url: ENC[AES256_GCM,data:S6YpAeNWEuD5GgbHovnKtdm4tNQ76VPSzNPjaZJyFa6pNxlMObb0PbEcEe0Wr1uawZEvt84KcWwBXSSP6wS//hv1aGmdXhIz590Cv+1qBt+LyuD4IiLSFw==,iv:8duA+fmoCZJb+8uigRbxnq5MpBXkPuAN7GSm1Hl/zM4=,tag:RAbIcW4VDfTtpyTVz/Ph+Q==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:Tz8d63Ns9lcm1UKBTlSo5vcd4YsUpMsufShUdunFTyE9Oy5Cz3Faa5aO3B39SNV5RR43zwsQTN8Crxq1YooguIRYGtl7Uxps5MONK1nPC0j6kNzMP00oOLm7lxlhZIXe6PmjKLTtA4rT+pyp/m5I+rhcBSQsTmtTBlAbqV0TPGxihrBD5XaUq6BahB48dwsuFjPSfXdYzjF7BP1v7B7cxUSwbnWulG5xaM9xxuEvowBu0oSNSEqrE9fBX0RosD3DTdnNGH6MhQYJKbDFT9/m4t1DD3hgcFe6tCwggPMYQsp7FCOSPfmu/Hy95vkkTzeXLJr/BBPnAWagCsIM4L7dEIo0uuqnJhKGQRoEGBj4aJvTYr0zf9fX1JNwhLt22/64B/sBUOJmWgQTekHPeMVP20/rjg9dgtm3EhDR1mr3PUWzNw02vAoeSkPnprK8uUCZgj8Ur7x0cbFziOqEuvIUsdDKbb2IANEMcFVNcUBbSQaX42t8J3QMumeGZKNWo92Wydu5b22yvm4=,iv:1Pm1JNdLBBlyJqlywd2NAF3Tc+jzLM26USc4PQXGR7I=,tag:5WqQPTYx2L3ypltTaV31eA==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:fB0TsSV30LPbnGttwaZOkO05fSVjPAqW,iv:YXmAFHx3MWBkWpSEJU1U4X9YjdUkANFfmS3k6qin9x4=,tag:NZKtbJLqTEzjroOwPxge/Q==,type:str]
            client_secret: ENC[AES256_GCM,data:rrcZgvNPtQWTcOq+bHGzDS9ObE9eI6YKxQ52jqv48T0=,iv:fO4t7JsiMi2x6QFkReUeKIYlrsNvUEEX6kiqGed03vs=,tag:o5MN3bkOJV969VvHNgMxMQ==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:I97Pgwl9eE5WHnAvVnlhykDwQWKO8S8=,iv:snazS2Od09MwmoJSLASA7QsgZ+Tx43Taz5VdaBpWWow=,tag:o0azuy5vgsbq2B9lOYwt0g==,type:str]
            client_secret: ENC[AES256_GCM,data:1DmTThCrqry1pazqpJ/WM5Gnc3a1kW76mN9DZXCLUw0=,iv:ECn+SIj2naPrW1O18U16ho7Vd6SnY/RXsvxynKEQDZI=,tag:4pJ2HuHH8WuD4g8rRkPSUw==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:4r9dkIPitE5OtbjxSj63OuudNugheFf6/g6F0L83SF7ymCE=,iv:uvX29U6A4JZ0uWtc+WEpBzI3t7AbqemRR+zpI7EJGR4=,tag:/P0jK9rI7PbsBNQXQi/40Q==,type:str]
    client_id: ENC[AES256_GCM,data:o8tCZJ4FHscHKIs=,iv:5ie4bA22mO+cz3pJUQPxq8NEAqNQI6cGIjdMCt62nmY=,tag:8uwqtG/IpUFbYS/odgxU/w==,type:str]
    username: ENC[AES256_GCM,data:R6K7UVHzImx33vwpBxlsHw==,iv:6yhHggVpJlQ0Tv8RZwUi5JSsiM8uGW1sw1gdEACi2t4=,tag:8wKXOdRbp3VKKss7FNJTdQ==,type:str]
    password: ENC[AES256_GCM,data:gG0qLFy1hjNrBdMbHUxrkjrE0ZMJ5cHO2zULeTIaCDK7tuvHggmfBTKgv2tSgnoHXt2m/dqD0XCm7LMMbR2lSdnzb3KZ0aCBe7KMfQ78hir1qgUtidwrPuHw0cNzvuDtFgs=,iv:ZU98B5W5t9NHr8rf9EdGm5dqIKXCmRdqQI6noVNr4wI=,tag:fX0ms+qmlt1CMXcibN+72g==,type:str]
    topic: ENC[AES256_GCM,data:CYAGFXrjSZHdK2lZ9fpkrL1fWZH8eG9PhkBDScX6tlfq4kSMHD3qGUWJ,iv:q0L/iCO2PmkMLUedUVBaTd6uTqpzTACXDn9KuvinXuc=,tag:3CYm2Iievm/SIFGOHjcpag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbU9aeEVBS0hHNEFzTGlB
            OXB3bGpXdU9GeHdFQ2lIekVnbldKeWFIQUhRCnZFZTVnUlVBdFlFQ09uUWpscFQr
            UWdhbXFrZS9SaGg0R2pIM1Y4VjU4U0kKLS0tIE1MUHRtMThpOFVQRHR0THZjdUVn
            anZhK1JxNjhLWWRydzhiU3cxdG1EdFkKGghpiJPmmxJGIL0BFeqk5GFYAN5E/lhw
            uX8kbRatVnftxbxySIGI2PqX4IWbG5OLp7vcQjbXHp9GyRnmXSq7hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T20:14:58Z"
    mac: ENC[AES256_GCM,data:QlXMT5fzN+d4vUr0vRjAuaGBebe9kBflzJiE+h09b/0gaXRUh+97AlT/uz+lutrJIdbYbjQEi1bUvEIcmnrQ3iOee8SdpiyB0lgLZpqGUVgeqU6SDWrxsGT+mgsrVCrREcZkObC/2iXqi/TYkH6nmt2Mmy/0bjWk+x2ICvo4xEI=,iv:vezVNaEFyj7+f0jMbMqILR/DD+vZZ7pQzRgqGNOdz+E=,tag:8mCCzysxzzouY8B6yDDHEw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
