dashboard:
    title: ENC[AES256_GCM,data:2OcoluX8gJc4Kqh/sUEo6PxXKbhk63/Pq6dk1cAlhg==,iv:yQbpZpamrVg9pBi9l88fWC8PJcxvWkgDpnl8J+oLoWc=,tag:KsY3jwuibZGdNAwhy7WG5A==,type:str]
server:
    port: ENC[AES256_GCM,data:w8Eaxw==,iv:9mXqSWK51Uk4vOMjtdbtFXSNJwTIuPvp6ZyYTSOrmDw=,tag:6hnpRUpHA8ZlqSH3Rx3VmQ==,type:int]
    development: ENC[AES256_GCM,data:6NM/yQ==,iv:8gUhkZeVdVtaN9x+Wn/Wy9ckv8TRHTauxesn9vHS9AI=,tag:XW1uPc5dQpMvLvafMvvXcA==,type:bool]
    app_url: ENC[AES256_GCM,data:lG2MckOKmRJZR+I576Bnm4CCwuSo,iv:HpZxZ7KSN9uZATofSoBOW5sl9g2V4jwkG3JO1MQgDYU=,tag:GR+xMpS7JiJ8Jax3XMqbKA==,type:str]
    logs:
        level: ENC[AES256_GCM,data:V7ZhDS4=,iv:cdGkHv0OFSqxOOadAcgY1rZsM2wD8OblxK4u/9Iri5E=,tag:5NFXm+uGLY+7JZY+jbnZaw==,type:str]
        format: ENC[AES256_GCM,data:u+sYtA==,iv:dF2MAXAvHDfwAiAzzSMmyoVM1iNq2PcE0r09xxFwHSc=,tag:CoI3bZYMAXgJNSeCrBzYSw==,type:str]
    database:
        host: ENC[AES256_GCM,data:FB2aQt2c+ZEA,iv:tDI6+z+d7saJvlwc7eMVc0OPaxAm9aPUsZL8FVV7VHU=,tag:Gzn8PmPen9l7vqG22MpX0w==,type:str]
        port: ENC[AES256_GCM,data:Kg04kQ==,iv:jvKAKQyak2pcx3GSMTSTHG2d7gdjwTFKhAC6NldYWGg=,tag:S9YAXsTC5NV2zS7nk8G/1g==,type:int]
        username: ENC[AES256_GCM,data:L7bgRnEgJ2g=,iv:5JDMQdtvj4kjOdClKS1ra/ddlcAxXJyyJtzcIFtP7Lo=,tag:HxWw3Z7sDAUOMY1jYFoxAA==,type:str]
        password: ENC[AES256_GCM,data:OAiOwdc6uSs=,iv:bbGBVUKX34Vg4YRyOVc19jBKJroWf7AlD/KMVOgPgGQ=,tag:mPvmMk4uuu07/ASnnf/rSQ==,type:str]
        name: ENC[AES256_GCM,data:bxXehuCFXXQ=,iv:2jUY2xKn1ywC/GKkUxunYf2R0pNLi0DuMdY+E4xdgpc=,tag:ecjLZE61Qejn6l3b4jXPfw==,type:str]
routing:
    start_point:
        - ENC[AES256_GCM,data:9FSBFnhmZ1MZ7Od+MjzMO+Y=,iv:gNwXj8pQNESf1JW873k/hrEjp6tT5N/bQW2+7aiSq1Q=,tag:tmccq7y/T3tqJVAK4pO5yQ==,type:float]
        - ENC[AES256_GCM,data:eqqJ2766hTUy0OEWFGii+Z3W,iv:3XNWGHoG+21VSn60I+gyguYzKxnLDh7RPXysL8llvy4=,tag:EHKSnrbxVxn+F4jIiyZzRQ==,type:float]
    end_point:
        - ENC[AES256_GCM,data:h3qWTRUi4bLodQv+a4ogKn4=,iv:07bOOJ3uaQ6WJ/c1+Jfntn0Tw/K2AmNFvDIIxgbC250=,tag:1IhMtJESYYn2kVyLtUyM0g==,type:float]
        - ENC[AES256_GCM,data:W2tLnex4wdoMFof3D0xYo1ql,iv:mDipBjuczS8QloVZYRb7+7Gn7HgXF/b0Zw9uaOijxV4=,tag:QiaaRkXezfiHIz/JxeYQaA==,type:float]
    watering_point:
        - ENC[AES256_GCM,data:dLbx3OmBWyuiUOyGnRYbb3E=,iv:J9xNp7QPr0ppxTAF4iqwOQGuy6cInO/xLhTLUQUD778=,tag:btM/2O8WXC2rQpjolU+L8w==,type:float]
        - ENC[AES256_GCM,data:aWRfVOQWon6Fz3XnOgQ7HBi4,iv:42hsml8lUsUxZDCSjiZA4ih2SAut0zV906AJ7P8/tnc=,tag:krSO86ufHf+oAMPJe6YZZA==,type:float]
    ors:
        host: ENC[AES256_GCM,data:9FmPoyYyz4HcbucXfLmlMjvRWYakJk5NBQ==,iv:WtAtEDBa2cnvnK8Uns4LzGHQIAEmOd7dGUHyv04kHTE=,tag:/Da23QPltLLpox4JnHAYLA==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:DEBqKQu4JJyILI+64PYMzr798miU,iv:GAVdEcKWeDRLHErFg3yma1pFGDqlaGfsCfFxC4SeTlM=,tag:czqfecvOI5/sh6QyigcqCQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:9exXmpRA1mt7LAOP9wzLzBQth454,iv:U1iqArIIwCpbRDMexPMYU5yiiWk7lMLcNTFJv426Qc8=,tag:JBVjZh/+Fc9+oHl3sD7itw==,type:str]
    region: ENC[AES256_GCM,data:PJf5QpU+HNM8,iv:mRNE1oKh1mKKCxgEv4a02QdOkGJZye2PCEMcscPr4Rc=,tag:+O8cl0s8H1wGurrskEPiLA==,type:str]
    use_ssl: ENC[AES256_GCM,data:B8uzPA==,iv:/W/quSPBvAkFyL6Xo9kaeq20rhqvRZx8dbca9zv5XmQ=,tag:dCPB64AXZ2cibvyl7KKsLg==,type:bool]
    route-gpx:
        bucket: ENC[AES256_GCM,data:Pb6E3ufWV3SZvg==,iv:oGLnfDCLOM7iu8XnuuUMs05AqYa8oIg2AI677OtjjDI=,tag:gu2ckUSLjHQYIfI1sRW9kQ==,type:str]
        accessKey: ENC[AES256_GCM,data:iJUVanEqR8wnUQ==,iv:uzdrRYdmArVrO2sVwatEeLdyBwq6trxjla0Nbd9c+1A=,tag:wKchbFBbMoE3E0a01c6leQ==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:O4zfXP6mWptbUPz8N5SnzJTusV65gI9xTu22qrH06h0=,iv:NMl9DeB5xlkmNzkEcM8ntyiK9qIAEPYNxsBkJCUY6Xs=,tag:NpRx3TKbMYK7p+uh737bew==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:Mfz7eaAjUA88OSd/P5A3pQVvR8OYJ1XUvoMM8ElOJA==,iv:3vfPb1/W47sXObGYqjIdj1+6VPu7eYCNed1WOoEITuk=,tag:v8clsWzrhPzx7IH5x2ZacQ==,type:str]
        domain_name: ENC[AES256_GCM,data:8ZVArqdyEa0ZR715eCiQrbMJEA==,iv:BRl0hO0mqrc4Izv4AgvJBDi36WrR45gJoN4Q5w9rNlE=,tag:zm97qJFgr9r3i11SHmo0iw==,type:str]
        auth_url: ENC[AES256_GCM,data:HGaC03TXuEV9HcV9/VbgeWAYFM2v2abq7p5tgRf3EG3122rRCXGI5KBgoYfncC1gnb4qWN0fDfuGNg4zWYfK18cJiga5JO0izEnxcYGqZA65ircU/RCB,iv:XFPs1t9PF3DuK9hkFgqNRE7+D/+vUWX8XnL9QmrP5GE=,tag:HPsW9ni0z0MCQjQWXM/dCQ==,type:str]
        token_url: ENC[AES256_GCM,data:FAJSCbljF2ZBlY12K+XFcc24aBZ4rkLZdke31rnNSdBwABj781AVV411PXSsIdF0eyACucqd+Q/2dJAGJN6lpxZqUNIZKwYsIR3wjR/tUesJIz+mPyQN0w==,iv:0qN6oVzsfGiooz184Dp8YhyAxmZW5tFoQffWt5TDoHY=,tag:k/+6C4cHWUCjPD7+kUaupg==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:b4cqpk8y5jOF5/neLEeb0AGsfhzDffA8R0lCyaDXVIQUt+wXd8YqFC6SQmvemUDV0Zoz0UItwx24L8hCWNm0miqTdV60ZKGR3zH6NwTnXuvCC33vOTs8ueuaQjFJmbovoptrG/25dch0j63b/fvFfLq5fp/+kIYYY8KZnBWcnUJr1ufHgDEWSfMhhZh/1pI0+xF/hXdux6+xfK71km1T70gH0s9Obltaa5+SlaZI96kjLh0qkGOdBpJXRHLVwcfhSNxEH4AHDsOKZmxqBiA8SCOssy6LNe2D+qqwGHKhFpyQTzmpbXK8pKQ1SwsT3JIAXYgqJxulnuHq4DjsRYmR5isJzKz8JOvVxZf3EqDKtPAxown3qu42Qye2ywA6mJ+87wHihFlsAvdUH9nYBkj4/WAXYMyufLWyQYAd6TuiD4zwYH2ElnN2d4JPPFrgSwcz4Ky+MYt2TQBKZ3MkQVZqnu5KxYpElhw1FYtmpigIN2gC7PxdFv1r24KoJHiPuJse8d/qBPezQpg=,iv:5wUWGhgQjzEFJfupAdCElM3NF4FmEQHUEmZ32Q4HJvs=,tag:krzDZCruSaFIH8rJFd5maA==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:ukq65BL0KMUoUmVfhV8uRsbLr4LgeknA,iv:YeYRYgtZiLGl7zNmSUOmOB5CprbcMPFBp7rCXN5DEFA=,tag:/gvahVA2hiNmvURl6rRbYw==,type:str]
            client_secret: ENC[AES256_GCM,data:DqUgw7CQNN4iLsDbKs7mINRPgPvQbASR/1jnogaap7g=,iv:cybRFpfNHqoux/aoweJ92mlfFD/DeZ1DVgv0kfPRhl4=,tag:FM46SqxtkxMFRVZf2d5KIw==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:a5lOc/GSpPxAJAERRbSuK7JS/9WE/x0=,iv:uM5eMnFcwZhgoCoflzZGb73FC7T5U3OExsZiyNc9Qwg=,tag:FZRA3frvr1a+aOJr6aDIiA==,type:str]
            client_secret: ENC[AES256_GCM,data:v9RH5oRe9wNvK9sbDlefiC9QEf9KmIH8j08Yrd/edVk=,iv:iEOHTjtXN2Ja4jkbShZKrlCp6miFKI6NxCeYbbS6xpA=,tag:PDUXDM7UhMvE7szaDLeo1w==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:g6ZMSHoXqLacX9ukOol10rQvRNztB8Wufia7fYTSFy6y/vQ=,iv:Fg+lgv7eq0ogV3Wb9mSndRAt7urWdoR+po7ucJqxr6k=,tag:qHZqBfyW1wYS1wjor+VL2Q==,type:str]
    client_id: ENC[AES256_GCM,data:d+A7bO26CnkzV10=,iv:v14FAeYR/6Ru+F+99j9Zplv4wZMv4PBKoTIIjsi8jks=,tag:scYKZ8IMuros308PkvpYsw==,type:str]
    username: ENC[AES256_GCM,data:RMhKhQfOmse5+KHF4FwMtg==,iv:4ZuQ4wpST5WBrJQwtimdno8Er0qBGnNW4BQNGTZup1Y=,tag:VkJOjZe5N2XITUAQnIewAA==,type:str]
    password: ENC[AES256_GCM,data://hhs6QY1hxYV9s8UN/NHAqZMl6tTPu8TTuaFCNj8mZlFg5eMNxoEXLkpxdzGQgw0aWJoKGCjm5K5ImXKKqMRVVGySmykKphpf0+5AEB0z/PSysevGTo7sf8Wgzyge4B9Ok=,iv:n/dADeRbSirrvvPwOrpZ/prIkAHTWdTgMWEivPYWHkk=,tag:ObQo63pzNJsrQrURCPJSWQ==,type:str]
    topic: ENC[AES256_GCM,data:yb3nBTSU+7zJYWrQ0eK5rpWecx7EFzAnbdxyvvMllVptPkNwlXXpBZo3,iv:0v1lIJ15DAr98IpGfTBsOsPAUaeSG6E3Kju7SAJkLTw=,tag:mMVw4Uk4LiF+Oy2Jf1nwqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VWxUak9CamJ1ZjdhVEdo
            OTJHenJCT25HTWJtbno2TFM5OWloSm5lVDFJCms5Qis3YmdoOWpoSS95cC8weEN2
            anJ3YktKTU1CUzNua29MNnRXbDFGUDgKLS0tIFdHNDJDcjNwNGJXRS9KZ2IrODZN
            MllnU1FOb0JXQ3hUV0J4Rm9uU1dXREkKJddkPNArx/1SdVolGNMeKHauaekUWAhZ
            nRrzniBMBP2lQ1rgIWqZkeePg7umOWePs0oakaGOWlzGd220gOuBvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T23:23:20Z"
    mac: ENC[AES256_GCM,data:MbtcnJZzwSMMGMyKj9bmNYauh1y1mZyiljBMRsKoy9t+HTz1DyQ0RC5KM+UDs2wg1ohDt0xjWfmPxxYnWl/c6zKruZTY/2NVuaD9JCDfsOLoVt8vlRSjER0k+HHN/VNDenM2+jyrCIlWRYXJl/vdAr3krI+JlY78jMTBy+5lETE=,iv:l6yMyM2jMFlmwyCKZL1WSBsQGSKq+qCTTBq8JAdNCxA=,tag:Vq7ugXMyKYIYRRo6wgP7Xw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
