dashboard:
    title: ENC[AES256_GCM,data:YxSiPwhJtHpPxh22pbn/rKxC59DsxT1du9v6yy6hVA==,iv:h8bxMY/6QAS8M4uIRqFuOyypyOWY1SxNImxNlSmDGUU=,tag:Xk+04Tmkd/+9BRBNqIrbYQ==,type:str]
server:
    port: ENC[AES256_GCM,data:Dje1nA==,iv:Gr08VeFlcXr/WOihdxLjBaVRBPCgFaO9XSlCNdrAZu8=,tag:ZQfbG3TTr+CSTaeYJpSL2w==,type:int]
    development: ENC[AES256_GCM,data:Dw9HgA==,iv:RLB4j7Lx57FHa+GYfPc6asn8iD64WAlDpvsBAwAXygQ=,tag:9j6sKLdWopR5uv5COfZteA==,type:bool]
    app_url: ENC[AES256_GCM,data:6DErePLVMPxY4wflZGQtCxaTp/C8,iv:1x1b7cJS2YHSbcAbmpoI4gJxj5Km3gTfD74Pg8GE+FM=,tag:ab/aI3FLJi2DR+Mx/sAKVA==,type:str]
    logs:
        level: ENC[AES256_GCM,data:0sQ0yQU=,iv:ta/yLYxMsoO0yickRWbkJjwhzv0pxVent5y7RmslJVM=,tag:NLeqiye3/4p/CCIoogiBvg==,type:str]
        format: ENC[AES256_GCM,data:Fd/iYQ==,iv:5EpJW2fzrXF+kVM70ceb+tz2xdU9hVkNCTeSrGoLLB8=,tag:0loG2+ucAiJBH/tOevaXvw==,type:str]
    database:
        host: ENC[AES256_GCM,data:FXZOog80Dt2j,iv:TA2nuL4fTCytR97LmNCu+xBESrX/6hiGBo2WqXJ3ZVc=,tag:0OqHxPJujF0g8Lle5r5tPQ==,type:str]
        port: ENC[AES256_GCM,data:oB2sUQ==,iv:ylvX0as7D5KvK/s5P2r+OvvuVBPK8FMmUIs/QJRC0Qs=,tag:STbXic0yhoh7A4ryqz1BZg==,type:int]
        username: ENC[AES256_GCM,data:4+GNH/K8kIg=,iv:xUaYt4WrKJu8trxrELQpe09OKTf7FHVbN9nCvbJYzro=,tag:Un6u+fyMHtfdIDx9mPwfMg==,type:str]
        password: ENC[AES256_GCM,data:V4xENqPSSWo=,iv:Nw7MhFS/+KP4Blxyqa19kHqM1Q35VIMcj/iP1DZXJxg=,tag:uOEJTHWp8/pobnv1iYH5Ng==,type:str]
        name: ENC[AES256_GCM,data:6yB3xQcB6ic=,iv:SwJSKTHl2aCe5PPQ8yaqu3cAt0/gx/PDurTD5a0YLms=,tag:mawRuA/v0ND3/vd7IOfNbA==,type:str]
routing:
    start_point:
        - ENC[AES256_GCM,data:BSm/F0QYfdqtPAK8eh/gVGc=,iv:otLgIl4hvBr1cXsFF450sjm/Wi/89Gy8jC/obtrePUg=,tag:6oSymw2XYTvDQMI5MwHciw==,type:float]
        - ENC[AES256_GCM,data:lW6DUqrEmCWoBwaLQ1PN3Ely,iv:RVZhRMSdwJRZtuD9R7vzl8BLhMTIJ4xXGP8zPkgPtvA=,tag:H2BQ69yef/jzB73yXZ9afg==,type:float]
    end_point:
        - ENC[AES256_GCM,data:Cmsv+WsWGNVwyJw3BurGrCA=,iv:bqGbZIt09BKPj4uQPiFJ/K/gzNNkqZ8vyWrzST2/mjQ=,tag:DA8RSUB6trZtbmDL/XGmLA==,type:float]
        - ENC[AES256_GCM,data:EuASVfc7Rcaclyv+X/Ea0R+Q,iv:c2MbsGjNotT23ANuhEQl3R7+y1tS4vTPD7j/PlhtIL8=,tag:mWsyiCMY4StMWv53cW4xBA==,type:float]
    watering_point:
        - ENC[AES256_GCM,data:5AG2f9WYA4Jx9Kj45RD51Ak=,iv:mXwdTYkUjO+1AUEohXo+zUTe1UhTe7ux9joN3LjVwCw=,tag:kCySWTwOA1ZXe5PdxX5jCg==,type:float]
        - ENC[AES256_GCM,data:eq8lmBxYMeYypc1kL++qhhLr,iv:nEY4AICEbfdvGI5Opny1FaGIFIRIbMkphxBbPtcasxQ=,tag:BYT2i0f1AAl85pt5Co0AmQ==,type:float]
    valhalla:
        host: ENC[AES256_GCM,data:nU0c1AkjZZYu9zEnAy0tMwtwpZtW,iv:TEHu69hJOJBfHSdb+oLthEKzvno7+AOktjGur9Y7yEY=,tag:ljsSsbGzgFKbnLPscU3tGQ==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:EB2LHvNeECsGGIG1qLFJATVjsluL,iv:HKPNDCSlkQwq54u9pd4LP4IFu+Q8PiuaWNm+prqcVxE=,tag:204wbYcf7B3FYwd5c3BeTw==,type:str]
    ors:
        host: ENC[AES256_GCM,data:0CZ1oXkZoHUay2UCSpVLIrilCxL/bs4QqQ==,iv:murV1Z/oPs03poiWtmx3KDzI/1Q02KFsn6IOUBxd1Xw=,tag:h/aS6loewa/2FLePl+QlsQ==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:YK3bjEw3J25sXDM+9YRnHLh6MsrV,iv:YckugTUmlI/ROzAkr3t5NzojRMgfR1Q3PmTtvaOVoJs=,tag:lv2uTGsSN71NXVQlso/GFQ==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:390p8iOjpn2d+BwwbpYKgHnYLgrN,iv:N11iyTDTpaLdDFawfkOIeMyJTSCo4ygGKQzmC5hphzw=,tag:iS8S3GGYOTXvlppsmtRfJg==,type:str]
    region: ENC[AES256_GCM,data:4OdcxCt2rgLQ,iv:7a5OIKyJzes5qEJ+FqkTRlW/Ly6s7uC0sQWiZUyGft8=,tag:S5XMqPROzwWrP0ohO67vlw==,type:str]
    use_ssl: ENC[AES256_GCM,data:vlTRYw==,iv:9R3xgWG21H1vyVuvylyF2Eo/hbITsC1IC5m46NlwNXM=,tag:jKGZBaTt3Wj6zzZiSjLltQ==,type:bool]
    route-gpx:
        bucket: ENC[AES256_GCM,data:wt/1RTQIDXvcEA==,iv:pc+h3yeZJVDMiSE+QYnqbSHoVEzzsHHYiQTgZ3646+o=,tag:4IWkdxoeJ33uP7dkjtMcng==,type:str]
        accessKey: ENC[AES256_GCM,data:83Pkd/71xqixOw==,iv:V1FYkyFNIAHWeFZSCi20VHriBmLuJ1Nja95Xelz3IEM=,tag:VFrM60M2MxWB2LGoJ/HZgA==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:61vkd21F9T2nqhrqCOsICjT5/ftNllryCm3WvOWixlQ=,iv:hlVt2SNkTnXlGOQYG+b2wZUiQZ2fLA+HpALcxTodOzM=,tag:9t74OYb5OLdisAzK28mWgg==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:Ix3WN86DR2B+xyg97TK0EQj0v3CY8U8KeqcsrxvqgQ==,iv:e1CsHJ6D2kipKiwR9CbAq6PILNgSTh2HF/RsRZ+CuhU=,tag:MSSbe4LbE7m/MAdVP2JWgg==,type:str]
        domain_name: ENC[AES256_GCM,data:x7M9BmvlQ38JNyT3ADwVs6iadQ==,iv:hRucJ2mvBZiWmpuBu8jJRQAIS1HgXTv0aenvvYMfPvA=,tag:mYlHqnJjHw0mzZjYqpSxVg==,type:str]
        auth_url: ENC[AES256_GCM,data:uvlNxQMpRTW4pp1SRrucoB4UiVvLzfHg3UG0pr0icp13Ghe66jBGj2z+I9yUP/H6W8gTAcweAbr9HpTjgA9TdF4QaG7blRvTg/Zm3LSM3JE813ZddU5Q,iv:gaWXT54FGCTANzhOJ0ckrE7Ajj0JmeFyLXkxINJNGrs=,tag:qs07061iScwStd7ve8i4dg==,type:str]
        token_url: ENC[AES256_GCM,data:UBcT/mfFwEbNvdk0XLG69If6rW1QBme+LPucRzW6S4pgvyaqg9MfEBy2lAYfH4EuWZTQWeHTxcRaNQ7so5p2tPibcTHaUO0ecylwGppOuxx/obxEEJTX/w==,iv:Hd1N+2wUNP+ORZL9Gor/K2YP7LZuLzZE0xU4anFJmj4=,tag:ywNakEMXHvplPEd2uPsfDw==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:7qMoaFCCvh2003wN5JTZvqBLrmZ4npcUyVMY9m7E1J0EYAJtbrwpU/LOxX5LuftjJjvmxmD8i7T/nRjJ5zki4vCKRiKh/HTxjqIN7xSFuolWUTvxHZFTubpMZzZsoG+C8ZcAIBW1ZeFIZQc6O46yN8fcimkerbQD9VnRJ8CtgahykigLHXlBJzM+psA2mJSMdZqr6ZW5HTzHk3n1PUcshp2Mc4FXfM6L1ImgUcvjDDfM6XmZu6PNGk7nsP+2qPO50XwVzMTcEdNxbksh3O7ckW2N2ViCRY5kzcgW/wY4zWlmjISVYInhiogCgx+dItYd0ncd6ZwE1AYjjjPjSP5UVN4Ih8bmfIXLddg0tAdM8xxKXhanUh5wtLsbZrQa6oKDl8dBX3lUFJkCGHrsk/LKSrTBDVh01d6CDKtjRMA5MpZxo6hIre0NI9zpRvevfJpHd+NcI2rk+ekHDVti5Ie3dQQMYYyraD2m77KlQ3LTOzrmiIppGi5yPyPjMn7BQLac4VRY4F10hGc=,iv:99C4ztcBeXhtWgRtJufGHxkBvTvysVqp6ZcSUh7c0+E=,tag:6hY86UKEc4UzYM2kvcr3Cg==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:IPqTof4M/v+2f0X9uwuT0RSmT7+50NGu,iv:JgdcJ5TPvQRxB8LJbMtOVD3cf6vgt3kkwh5H9nuntvk=,tag:wmuvAnkjLtAs/zhu3AWDzw==,type:str]
            client_secret: ENC[AES256_GCM,data:4DD0BOpBAyGgWAnbDOcbxdQsjR9O2sB2O/D4yFrOy74=,iv:E7+USY7jJlBoMwTkMAwbVGjs2sf/NhGX+0QacTGwBxY=,tag:LgVQbpfUVyRkfK9FNkyJWQ==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:cWXlUSwGcOpUmyyK88uvVLhYAikdaV0=,iv:2I6TezlKAlav8yg7FUPsx03HEac5yCo/xP5/jejoOYg=,tag:c7KB3VoWejcE1ebr8KzbZw==,type:str]
            client_secret: ENC[AES256_GCM,data:wOLyehdSYPrCYXhavXaf2b+oKkbp+MfPZ2Xl2SVvchM=,iv:Ed165kfpCaXyP7lqAGWk+9Y0KlA/ICnrR/xWipRpicU=,tag:OD4xwXsBPuuXngnywyA1MQ==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:Rjqwfsav7RFH/7+D8ubHj9782KzQKFXVO26tKZA5muXLkSg=,iv:CtpCo8B6+SgubgSE6zsl1ykrjc6alkEtZrq/95GcHLA=,tag:7COi3j1Z7P9ZteqaE/3RXw==,type:str]
    client_id: ENC[AES256_GCM,data:lyELJE2byZ30y9Q=,iv:C/pPtOeDGTRGoLAGIXuFCrWE5nnOAe8BG5BMuF2TxUU=,tag:FbrMHZvqi/B26wQGy2RJ/Q==,type:str]
    username: ENC[AES256_GCM,data:GJNqd4nb85ihsGeO3qgDYA==,iv:JYSGZAQrIZVSKqJ5pk/IfY1DVm+WBJAMlCjNBlmzO4A=,tag:wMOEtn/mA/8SffqdMaSZqw==,type:str]
    password: ENC[AES256_GCM,data:/fYnxDwobQ6K8ARrObtkjXWv1Z7Nxq3QlXDTSGR5BidRvykW9lRllZHnVQk7+IrlBL/ErMGDGzH0LAB19lyVZMrF9NvbqpG7QYhiQtnW97qUHqH0NviCzjtUh0m5hIFkrWc=,iv:Net2yj6porfQLESdpaVu9UyyYpQxsBltVDSQMVbpUdQ=,tag:LwIpPvr7ZNEwmuxh8giiOw==,type:str]
    topic: ENC[AES256_GCM,data:XB8CJF+ajTa9Qel59upXW+/WSXyPUjL+GSPJLM6EdT6lYpoBC/4kg0z7,iv:RhrBZ4Pgcu7UWG+60mnxwBIgdRE+RZ2Q1KGHVSHgeL0=,tag:wTdkVUh5a+Z0o4INHXOR9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WXU5N3hJSDRWcC8wQmpi
            UEx5cE90WSt1UDJDT3JkNUU1YjRYaXpkMTFrClErcFIybmY4Y0JUVzh0TC8xcTZL
            NGcvR3hncHNtMmRQUE9mcnIvK1p6S1UKLS0tIDlnREJkUVB6bmZqb3BTYncyZTA1
            TG51TzdYYXdsSW1TNmxUOGJlekJtQ0EKEgeTUP/e7f3y4OMtJWVDR0PNyjfeT812
            95Ay14BDPN8MYVPZz7HRm6t5YyodgyRPWE0vpXma/Gfj2ErxBO0heg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T12:55:32Z"
    mac: ENC[AES256_GCM,data:HAfaq6QxoL05r9uDtZ87BH4ePHGEs87fZxPNvc6tSg/w+QCFhoc9bOqP8djc3BTpil5TtaMlSuVRR+c1g3YBICuS8mcqFHKoPkV9BlgRoEsiFOBKA9WJ58YXmwDblfnh34OPVgROyvuSTWZT1NhyDYoDVvtLS/fw8lD5p2B68+c=,iv:gLjcyNmxG6WVjpQrl1CI1gIUD161jrGoZoX40yHP2dU=,tag:087GhUIZNPyU8xL21uh11A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
