dashboard:
    title: ENC[AES256_GCM,data:pzN1HupGmjJeZyZe0skj+GQbO0wXUOTQMtESpcK9rw==,iv:mSQCZGC40TMzzWyWvjb5kU+/f8JWQg77XHcv7s60SL4=,tag:zEPADM7yhWkYZUOQvDdG1Q==,type:str]
server:
    port: ENC[AES256_GCM,data:RGEsKQ==,iv:fekzJmgWd2fbDn8eKmUUAfP7TbS7yQ29CxGzvJdcDzo=,tag:SfkkYLX3m73wmVQqo9JdCw==,type:int]
    development: ENC[AES256_GCM,data:y6VFFg==,iv:piipZCTsqcIkr0VjeFzFP4tvmCti/PGnzHDa6yqsgPg=,tag:7YJqlWE6DwItbc1es1Kixw==,type:bool]
    app_url: ENC[AES256_GCM,data:M/7ibawgs+dqEY14P6dWwB4C1tzs,iv:amsRvX8eSapxgAfvjZqaPBgYMSWU9lrQQBFFjDu9vmY=,tag:6x/MujOUifzZrsnKcixrIA==,type:str]
    logs:
        level: ENC[AES256_GCM,data:RM2oX/c=,iv:ccdD9ryQgvAwETT1DKchp+Ht/qGg+xtroirwlUf8ELM=,tag:n+HngMOBJp1AO7lWZQSNjA==,type:str]
        format: ENC[AES256_GCM,data:QBBRrw==,iv:IN9JxU5sFU0h1bDO3eovotMhL+hKpGaEPWWPIcAXB2Y=,tag:4Z20HEd0bO5WukESVM4JEw==,type:str]
    database:
        host: ENC[AES256_GCM,data:ZxbovhcXtDMi,iv:3cApHlcH5IwlxZ5/v3qqct57LhbBNok+ngioZjEGpZM=,tag:q80YBOURiL/GnjpxZQxLXg==,type:str]
        port: ENC[AES256_GCM,data:CxWD8Q==,iv:r9cqUj4CNQ5EIR2PL0owZU5f0qdQPON/Y4uO4npGOM4=,tag:AJ9tfDLwcyNYcob7s1l1Lg==,type:int]
        username: ENC[AES256_GCM,data:s/Q5mMGkbO0=,iv:7wdfVQHyt2qfuK9kvlp14FSsoPJQue0UH5nroCHgOOs=,tag:e7fFrvXZ2xysk+HI28uYKQ==,type:str]
        password: ENC[AES256_GCM,data:yfDIIP+pWhI=,iv:F9BQ2NmHUBE/hhsw9k9iokulNPdwIQT60iOX+AWAocI=,tag:gzKtYm4QOq3XWLXvSc9sKQ==,type:str]
        name: ENC[AES256_GCM,data:LQMroRNMPss=,iv:eHR4E8am5KHzIlOWx9iOEq+HGZERZPLQ1q3m3Gml5PQ=,tag:52i4a6HF4/Zv0wDAAAnEcw==,type:str]
routing:
    start_point:
        - ENC[AES256_GCM,data:ZtG0EhrJqUlZnFSs5eNgayo=,iv:DnJRgiYI5GMIklUsMpVfgl84Mp7kK38Cm50t55RUGsE=,tag:zhl3j7KHUoTN+zzCWoagxA==,type:float]
        - ENC[AES256_GCM,data:8a5hK0//L1iFvFZkzTw+LTLJ,iv:JcfW4OvEdf4jcxzm8tzfsuoogLWB2wXm7o2vsXEZtEU=,tag:3htB71q2qHUzCJ/Dryqp2A==,type:float]
    end_point:
        - ENC[AES256_GCM,data:Hist2KjhHMjNRxBhm7ki+AA=,iv:8/MZyr0tALvug7OHZTOgG9qV4wPdM66OqBwDiqxSBS4=,tag:22Pg3JwN2KH0BiQPvWyt4A==,type:float]
        - ENC[AES256_GCM,data:MaXdCt6gX0xRpP3yVDxN1PFH,iv:u44DxiGv6LJldNvLE93UacJEW1rDyZ/CAVa7sa3WdDY=,tag:C6m4Wj/wELBWD1e5RRPv1A==,type:float]
    watering_point:
        - ENC[AES256_GCM,data:QUfrEUhdndw2kFeJj0jyoXE=,iv:jj7WfSldC0Yr4xVVKJki69lGI1/nHA6Ft7xKcfvRCD0=,tag:j3Bxa/k9SISTRokBBAB8dA==,type:float]
        - ENC[AES256_GCM,data:+wG4MWMtHE1jw8a033PPbWxn,iv:t+kjvDIvIKQm4TMAI0dBvBZmAqTO9yRfpdZnZw6wv9M=,tag:T8Ar1/nO2LVLoo93V4ny6Q==,type:float]
    ors:
        host: ENC[AES256_GCM,data:V8PdE3M0/gYlzYf0fy0n41xGeUDyOU8JWQ==,iv:F3IJscDKGc3WkOWrPnWyrq+F/c0ihSneUj+aIrynZbU=,tag:Uq12rCYIr8OOl+M9vfluXA==,type:str]
        optimization:
            vroom:
                host: ENC[AES256_GCM,data:7+alyTzeHQhVjW8n4F5dUMdrC/1/,iv:/e++Efniv79nZtHVVIvPjHD846E6Lr04P5yiJHn+fmc=,tag:Urn1D6PJOs0UnTVc+qDtsg==,type:str]
s3:
    endpoint: ENC[AES256_GCM,data:TaE3LaDAPQ9rUKRR6RgncJauIOXi,iv:qGJv5SLB0ykwFwXKMQLxxdWEZWSiSmnA60WN2uiCllM=,tag:LwrPgjiXSl/3jIpi6hP9ew==,type:str]
    region: ENC[AES256_GCM,data:t1wpallkgYv1,iv:Yypy1IzZjYAzyEW3PaAAs921WMomT3bo+Eo0GiU5asI=,tag:ASPahzMnXDx7GK6XwnhoJg==,type:str]
    route-gpx:
        bucket: ENC[AES256_GCM,data:dO1/txu7hdoDtw==,iv:w3FUiCwUOKzKTyduP3zpGBXKuTrUnksG8l7pVovAE3A=,tag:aHVWV5ienVNLr4xTAnGCSQ==,type:str]
        accessKey: ENC[AES256_GCM,data:aK8FE+QI8FRkmg==,iv:OQAyEnE77n3/rXYtXZOs+QRQ8ODeYjuVjkcn/o/QDOg=,tag:Uuk5U0FvQM+F7vJZ+sRSWQ==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:v7y+DcOxL00dZUcP4fVbMcKUNA29838Oih/pM6I79yo=,iv:A0BSQ+67ICG41/wup8fZ+EIcY1EuLCCywlKHiN7tzJQ=,tag:3H01S+nuxhm5GjWSyvQ43A==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:3BxAH7sWYtN/uDUsMWnlHdzTYume46PMGMOu7/qV2g==,iv:JJgueyWK0e9WpdUf10Sd4KDOiksuk//USXzgO9IElQo=,tag:rCPNqLrvIEPqoC/jZfVFeQ==,type:str]
        domain_name: ENC[AES256_GCM,data:qEoIpw8vg7pbhPXyFh6llbhr7Q==,iv:g4AwGmRhifE07Syt9iPlknYk0dIFxLmjwxZNXaZb3UY=,tag:sdrUiiYsYOA44s/dFQtcMA==,type:str]
        auth_url: ENC[AES256_GCM,data:5gYXWgANpJuvxmFYLTvgKNY4LjXTGlJRGzMfPsKPd7ZXdoUnL7mjeGvM06YSKzy/fvDKtzqCWAGXabX5XTf+EGv9vqqHSJLaGaGjuBppK+56GsgzZ+/F,iv:6/NJtPsrl3sG4yXE4o2w9WLPqShFwFrG9uAiO/bwEHg=,tag:2MzjWiyFNulXw5BPLBIxEg==,type:str]
        token_url: ENC[AES256_GCM,data:HfhfHeNEdzb7ZT4Ue5QowQUxV0MfOsikexZyzKFd/XgOzfORpQH5YeuBPcZQelq41o8K61b5KCBYUTnbI0ejLVQOyxjTi/djnNSNrqzomQO2BGsMW08zwA==,iv:3yrhlLc9Yrr/8FFyAKGNaHS+EQhhzD2XaKdxMB07SwU=,tag:lcosvulom0aloiLyH+8O+Q==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:JgIcJ6a/Ya8fPCb1yIX3GBbLrRAktOazRjmgUAgjSJ4yrCQBan3GWDEoOox1pJa938sIpB+ZHffVydtH8iEZgoAjqoRPJeaPLhSxyMrV6ksqeCPQIzNndXF9VA26NMi9TXt3aIUngWxCfgf7E1EUtNeh80tkqW1y711wh4mL7fVzfT69rFaeG9/cMCO19uNBzxl9ueTSf4n+A8kMyDezIXuCRlG/D2F8PYZ/CZxO/HVpC277qpT7rFWmJoG9Av1e1UHMJBi7VIPXmVM1S78FCuSb+Iu37H1TmWVaVl8LWKtJk2MgCWKJZqQCXj9cRfwUp85lkbndeJiJEXXmT6S/oPO/a1RtogFgMbC/6FTlH+fI/L0yfj9ZujMTOGMXBPVWNPnLiTPatlbMIoV80DFm2A0TF3xvnMRXeloUnn/y6VksmZuUi7G0iN9fx+qC+I5i7ydwbi607KgRd6o9oPs3EgPSqsnWTRr/kArQo+nyjRHf1A6EBa4pUEti+qS+fze5LNa6FjU32Z0=,iv:IT8Yy5LK5za/s8ZpCE6y9oxalixQztj1jGlXXUMOWXg=,tag:v76PJ5XCyp5mmA8htKFzmw==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:ZcQESk3kvNsyO/8oOsXmJ2QSIEgR2Vlr,iv:sqwN8VUFqEycyh5b334nWE6dVQRLFQgFDlW5L7FO7kk=,tag:EGWLm836wrq969+XYiY+qw==,type:str]
            client_secret: ENC[AES256_GCM,data:YciacxF8g8cYDNSk6yP0TtBX9Rz0CAkLwee+m/jQviw=,iv:qPAM2dv1Xx3JKsdSjY2TWgpyp60q8BwUgzxiyZDuEl0=,tag:SVaznhxMjDGAjlUD7RRUoQ==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:TVHCtR5yfedmXDicVRBLObjXFKQV9as=,iv:RUf+koqjcTi77fty1GHFRIINAxFzat3182mG9Uruy2c=,tag:Jr3CHu1gyYtD39DAqImg6A==,type:str]
            client_secret: ENC[AES256_GCM,data:tI5iqsFFMFvcf5kmYqQG+tlZjdmerJlPCbnGv9eEicI=,iv:xhqiIMbwb8lSg++aun94P4I2jIYW+SvkF4JhydTAkrk=,tag:DlOprqrGA8j1agCErXCHiw==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:hUI4OjNvdlzi4rHPfhQtW1BkoBbuowdExJMb3xMcF5y4jf0=,iv:H45onELK6wmjd9VWrJhUrPv2B7dLGhuL9OMj/pPYFlU=,tag:9ULQQANO9q2Omq8vLCuw5w==,type:str]
    client_id: ENC[AES256_GCM,data:k0TjEuKhVeyTnyc=,iv:5lAjLbsH7GTf8gsghiasqVbcVjv6dL3QbnkqFwrntN0=,tag:J2jPmGemvJeRtfofpFu6MA==,type:str]
    username: ENC[AES256_GCM,data:s5ITVtZnyputywz2V4RwVA==,iv:9Zh9eoNdk7UdZ4e5Esc4mYYfAihz7B+AUwBzpOK9Uq0=,tag:nb7bfnuT6mGgcWD/H9nHpg==,type:str]
    password: ENC[AES256_GCM,data:ecw4YguWpjn7c5EDcjc4yyx8dvC278Cd7pZdX3hIvCEwtmCBBdDSKrRzTXjJ0dxdBoD6YHrpA2wK2mGyYlzb8RoUFqYfBTVU6WvSxVjK3dCCIK+dDFwlcEVoW7SMkj19E8g=,iv:icd9peXC5jtwpdV79e1K4YJEPmLucITGyHbALc3m/wo=,tag:cLOjHz1hxbJrHErm+rYT2w==,type:str]
    topic: ENC[AES256_GCM,data:2PMQ3OLz/oqYtUNQrzq6YFACg7CFj88lgLDpkrjFzPfOj7iF/2JYY/QJ,iv:meawaQGd6ybnAZKjOqIJXjuirLNOktFxtrxTTdgJVpQ=,tag:OIIj90PdbllDwsy4TTop3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWjJCMUE5T2pjS0J1NHYw
            Ti9iZGQrQU12OTNvTEZ3K3FyUkhpMnBEMUhNCnU5N2lKNDM4TTlIYWRQRHFtZGRt
            WTM1bnVnb0N6bkhoOWdHSGhidHhObU0KLS0tICt0QW5xVGc3NFhjcEcraDloNUdO
            d1UrT0RrR29jQ0xQcVBqYlE2SERKcGMKIReTSs6YqP1HBuSn1jXFpLT1DS/mv7CE
            B1bJUt+6bx/m172W3QIaw6Z48WDZXb2sOTgLpeZFrj4XsqAEnnQTCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T19:23:59Z"
    mac: ENC[AES256_GCM,data:yT75eS0TR6EwHLqykCHfg/cY6Qm02drC1ssH4l3z5fwT9USQab5wZIZpTbd6vnpH54RsBmEJrjGBAQWia3DEfgB+6mKY5LJgutF25eGaYtawv/P+91Ev4PGgZkSW+6QEP1RJmnD3DS41UHb/1Vv8KfXk0KcSRYWbRCl+PqqP2PI=,iv:4MPoxZT+BfZvLN9vVoO19Yy6iMO02LCqDnOqmp4Q/wU=,tag:d0zw6+YMEETNvHErL2tEcA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
