dashboard:
    title: ENC[AES256_GCM,data:hvjDb5kJcQRpkGzE0kqjjXP2M8nNFG0XCtiZ4wsaug==,iv:wWQbGlDSjrOzl3ENzseOKn8kHQgkFT1MX/UMw0FLXV0=,tag:skYvFoW91bYui5W4b5Df6g==,type:str]
server:
    port: ENC[AES256_GCM,data:o7fv0Q==,iv:0wGwrWXY7HCcnCi7SsDfzodXaYJQzFoUD22x7CeY0RA=,tag:cF0PY4yYjREFPWwxn/kLJQ==,type:int]
    development: ENC[AES256_GCM,data:Pa8XJQ==,iv:NRhKi3yjkFnMXWrbAgQhawCWwoidD6s0gjfecm1jKt8=,tag:vdOqrOEGOgjhL8/hd4GuzQ==,type:bool]
    app_url: ENC[AES256_GCM,data:5x903oQQP8sud5O4RQn3Sf8uwyVm,iv:Dm24jtzz3o8PP9ef6wSN6dLHa7OgoxlOnnaFYNzNjg8=,tag:LHtYj2k4mqcvtTGOIe5fXw==,type:str]
    logs:
        level: ENC[AES256_GCM,data:r8diTi8=,iv:WWfp5iZvW5q2cnyn8FKcvXWvbKhzl43LcNtNNp1A0Qc=,tag:lDyRk8qcLXV1FTLZx2gNcg==,type:str]
        format: ENC[AES256_GCM,data:mHAzxQ==,iv:cQJeYLNkeGMYhhmSGGGiNc/H/HNrnIfzn+D+hzDSjgU=,tag:BPlxDoaovf0qcGzbbpXZ+w==,type:str]
    database:
        host: ENC[AES256_GCM,data:tXPxlMgCURSi,iv:Lk4RsDOrUfSqIPfDRqTP/jg4/N374ZlTw0YQ1oaxbLI=,tag:7XX2xHTKDzsCRuAj7sU7pg==,type:str]
        port: ENC[AES256_GCM,data:XwqT5g==,iv:8oA/7tOzKiPzl8h405rluaKYAvOE9uG3oiLCXbyvDeE=,tag:ODwpXp2XGTxlyDEoK1hd0g==,type:int]
        username: ENC[AES256_GCM,data:2GImAlUbF28=,iv:X5aaybzIYbELWFG4HKo50GYp0u7Zcf0uKO/jdZVNPA8=,tag:aNHUS0BZRfD/ljI4SGz7Fw==,type:str]
        password: ENC[AES256_GCM,data:4Iz2NBngeRo=,iv:kpwjcQPI1P5lB531WjJAZNrmvX5SeqInM9m+6P49Xhc=,tag:V0mbA8Txh7A0okfm/EmFnw==,type:str]
        name: ENC[AES256_GCM,data:dLpLQEL9/10=,iv:W6rWcWJdBhD067HJ47Ep/niUT2E05eJKbqha1AQ7PCY=,tag:eiYv0X6PnA4uYYMXtOJqPQ==,type:str]
auth:
    oidc_provider:
        base_url: ENC[AES256_GCM,data:Q4foCcao2Rf8+NzskqR0gz4AfmWPL657YPMkXC/4pw==,iv:eiizvojXOD5o1xai8uvGXussJLInvuhn9f3gwTijGdg=,tag:Pj05DKnCHV1Jq8noffv9mg==,type:str]
        domain_name: ENC[AES256_GCM,data:FQ8CyL191BXgB0EfDj0gGSEVbA==,iv:HL2FBdhZbfZH+38deF3QOc4q4SA6IUTi/tdtO78l2oc=,tag:XQ2nq0WZ+uxkM+AdjHvt0A==,type:str]
        auth_url: ENC[AES256_GCM,data:QvQQYjUf75zbJLSaAN44IcAlRvWeEEvcdvkSaedtwv5uzNFpezzA+jz2gAJBigRSOr4YQxLFg7/L/cSe3mTfyCt4ealEJfUuICrnmZek5WH2OgEBSPtX,iv:pOv84y1ff+67XtnSRCEEXlXmOm0yBfPW4BnsRld5pEg=,tag:5/zdSQqS6riqqYINJiDyGw==,type:str]
        token_url: ENC[AES256_GCM,data:IhZf7X04tMps5hTv03baWeXIzaktbK4dMc7ghvBnKnOwNtNq0qVcJYjVRaC9OEetsyQLyYZHmlwdRHrg74phnPpTuUoijHujQq8Kcm7e8OvXKlEK7mBnKA==,iv:ksJJfkexnMgstmxCLsYV2JsODZZU01RltTXrHM9b2fE=,tag:gRmeDKNISAclL288yZfReA==,type:str]
        public_key:
            static: ENC[AES256_GCM,data:Mg8/uy9diMuO6dB20CpLx8r1bHDBuM64zhUMIS7jNDq5yLPhqgCXJ6bXdTkfyP+YhHCAtxmT8kC3eKUmozZD6bfDfyvSmczdEMpk1ff6V2dBzXKvac2kBlrOVoaKR5R+5l/pNsYGjpAF1SsMoRkewdAkLpiIAgTYTUqEzFmVYRoxL4Uvfp4VB+UNiqQafgY10qeVH19eziY8ApIcFLZmopXZ2yyxiQ38NuCkOIe5+WGGf30Uox9yTHFaVh08909tIZ8KD/W0Qd0+tPOorj3BTSD33UzKtK6NISNY/QLi8TXHeOumFme5JhywTLHUU3gD3tZHNS7tLJBYuajLgAYCLT7vo13n+lh2IUe6aTc+GTTqh5U3gwD4HnYogXwQbIzAD41A+IisFWyW7Ajdma2jqeaaMGHC+GlQZnijvSUOVSQDgHWn38qkgnP0BsaTZc8U08OIVb8CQrTWQSnQQTR6DNEK/cY43rM9wdt0AHUoToqX4Nov4+JIVSH5MPfPHGdUOqyITxALUng=,iv:qb5Exz5zb+yPyeU8Zw1QYmlDQLCfjXP1/hydI9exePc=,tag:fR1k7kYTHB+iw1PV8BJDgA==,type:str]
        frontend:
            client_id: ENC[AES256_GCM,data:ooDpS3/eIAuILxdo5/gZeYjahPhpdqYt,iv:r8qHEUe5x1AxYLfkm89aoYS7ibpPF1ohxGczYDq+xCs=,tag:LF/PvCmR0U1HTLMdFlVqsg==,type:str]
            client_secret: ENC[AES256_GCM,data:3APu37mXm48E76s0McXEGEgyHtS5zJ8SYQCpVWyxy4s=,iv:6DsSqB8KZ4BW5yEUdvzPp/a9Plr2Vc39KEu6Z7w3JDY=,tag:RkAlOG5sa7ANt3itxbvAug==,type:str]
        backend:
            client_id: ENC[AES256_GCM,data:rIRw3jVDLRX41/fn3Q6NWOJCc6p4fe4=,iv:eACWHdzS18y9WcicLpNYNT7NZV29iFrtjhZb9OvPzpk=,tag:X6RP8E5uvjVuv8032zOa8A==,type:str]
            client_secret: ENC[AES256_GCM,data:PFVwMyvC5nBwx2R5BTVxB0ldqUHQbP9DlPyaZUMp4RU=,iv:pHxWNeS/4gdy60AxMIQRWJviPRx02bV97IMZ2lwAYE0=,tag:W0jVFEC5FZlI/uccjf+fAg==,type:str]
mqtt:
    broker: ENC[AES256_GCM,data:hwLIdSSPUuPnh9+e3SXqnx3hLN0+Un9B8289tcVz7Jy74B4=,iv:7avUaJR3+uRSco3DVTo2imu/tldgHQ2eeEVQtoEzHW0=,tag:yMc5pb9jdMOQJqYuF2g4gg==,type:str]
    client_id: ENC[AES256_GCM,data:XPjPd1ZY75/kZ9Q=,iv:aLFHP1TqverO9fkRslUQwrsmuNfsg0p5fuxSCn5wHVs=,tag:0e7Xn6QsSmZ+kDjYo1F4rA==,type:str]
    username: ENC[AES256_GCM,data:dE5M2MEHS1RBexhrPHo1Kg==,iv:5Io3vJnNRynrG8t7eyWJ6NgSIDu+9v5fsJmGqpoHD0s=,tag:RB38jFEE9Z+y1KjModVdgA==,type:str]
    password: ENC[AES256_GCM,data:PxaIX0XJFoG/EPrH6EOgalLq+Wn5LlemAPdNXbfcAm7hIWegx2KrnTDHngtJ0te2bj4TiCvY54xas69oSY1J0mrV7rz6qlE49oXO04kx4d6Xv4Cbn1s5LEn4pcPGuFfSdVk=,iv:dRb7s9SiQ+I8fUy8J8gAYiACeXAXiptSIbMwYAiiuh0=,tag:6qlcL5LWTu/viPwFEZJy3Q==,type:str]
    topic: ENC[AES256_GCM,data:VcWN8L97RJCMaJRBTHstXuqTDWl2llU4dupzIybPrsnC3tFiLPG4+QUi,iv:e6dnktXZn4YCbcbkYhSLYqoR8PsbDx/oCQ/qnzWHanE=,tag:v11zfX1+Rotj3RRqEh0DVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVnVIdnFkV00yY3ZTalVR
            bldoQ3FSZ1FEOUMvVFI3TzJGV1YvUHJ6V0V3CnhsSVF2NmR2Ukk0TjdYaFVFc1BD
            bmRsV1J6ckdIcEN1OVZuYWExL2wxNXMKLS0tIGU1YnlhcXprd3kzVFErZGVyS1pN
            bXVCbWVBWnhNdHJ6S2tnb3plSTZXek0K2Z4tUZNagHmazh/855NRQ92z5qlXf76h
            VuobaoJdT2zIWUDXXMXcRv7AY+ao6kr/UkOFWbcApxX9ESR8IO1Brg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-24T19:35:33Z"
    mac: ENC[AES256_GCM,data:j7yPw5cAOqw3cYTr6MeIbLTBQEib9NHS9PEEbYHsF1dOiOWohzlsl3RKNhhA9Teut2gfWSMYnF2dMyVTOVK5BEoabjkwGbno7vcmS8/x3429jQGLbANuhlD7yZArmKbs1G1msKklNdOmYpgYyeB0aOG9HHKINe9ZDuHnWj0uqPs=,iv:uUQujn5V007546bJTeRIBDunXP7Ler378eMBfN7uBzc=,tag:Y5kmAr2NIYqek+p0uhqFVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
