dashboard:
  title: Green Ecolution Dashboard

server:
  port: 3000
  development: false
  app_url: http://localhost:3030
  logs:
    level: info
    format: text
  database:
    host: localhost
    port: 5432
    username: postgres
    password: super_secret_password
    name: green_ecolution_db

auth:
  oidc_provider:
    base_url: https://auth.green-ecolution.de
    domain_name: green-ecolution-dev
    auth_url: https://auth.green-ecolution.de/realms/green-ecolution-dev/protocol/openid-connect/auth
    token_url: https://auth.green-ecolution.de/realms/green-ecolution-dev/protocol/openid-connect/token
    public_key:
      static: secret_secret_secret
    frontend:
      client_id: green-ecolution-frontend
      client_secret: secret_secret_secret
    backend:
      client_id: green-ecolution-backend
      client_secret: secret_secret_secret
mqtt:
  broker: eu1.cloud.thethings.industries:1883
  client_id: tree-sensor
  username: sgr-students@zde
  password: secret_secret_secret
  topic: v3/sgr-students@zde/devices/tree-sensor/up
