services:
  db:
    image: postgis/postgis
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - "./infra/pgadmin/servers.json:/pgadmin4/servers.json"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: geheim
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"

  ors-app:
    container_name: ors-app
    image: openrouteservice/openrouteservice:v9.0.0
    ports:
      - "8080:8082"  # Expose the ORS API on port 8080
      - "9001:9001"  # Expose additional port for monitoring (optional)
    volumes:
      - ./infra/ors:/home/ors
    environment:
      REBUILD_GRAPHS: false
      CONTAINER_LOG_LAVEL: INFO
      XMS: 1g
      XMX: 2g
      ADDITIONAL_JAVA_OPTS: ""

