name: "Build and test project on PR"

on:
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install mockery
        run: go install github.com/vektra/mockery/v2@v2.43.2

      - name: Install swagger
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Install dependencies
        run: go mod download

      - name: Go generate
        run: go generate

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
