name: golangci-lint
on:
  push:
    branches:
      - develop
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install mockery
        run: go install github.com/vektra/mockery/v2@v2.43.2

      - name: Install swagger
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Go generate
        run: go generate

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3
